package cu.gob.ith.common;

public enum URLEnum {
    LOGIN, RECUPERAR_PASS,PRODUCTOS, ALL_PRODUCTOS, CATEGORIAS, ALL_CATEGORIAS, PEDIDOS_DESPACHADOS, PEDIDOS_DESPACHADOS_FALTANTES,
    PEDIDOS_DESPACHADOS_FACTURADOS, PEDIDOS_POR_DESPACHAR, PEDIDOS_CANCELADOS, ALL_PEDIDOS
}
