package cu.gob.ith.common;

public enum URLEnum {
    LOGIN, RECUPERAR_PASS,PRODUCTOS, PRODUCTOS_CON_EXISTENCIA, CATEGORIAS, CATEGORIAS_CON_EXISTENCIA, PEDIDOS_DESPACHADOS, PEDIDOS_DESPACHADOS_FALTANTES,
    PEDIDOS_DESPACHADOS_FACTURADOS, PEDIDOS_POR_DESPACHAR, PEDIDOS_CANCELADOS, ALL_PEDIDOS
}
